default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: poolscope_development

test:
  <<: *default
  database: poolscope_test

production:
  <<: *default
  database: poolscope_production
